# Generated by Django 4.2.3 on 2024-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppOneSDG', '0003_alter_booking_bookingstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipAudit',
            field=models.DateField(verbose_name='Last audit for equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipStatus',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status of equipment'),
        ),
    ]
